# Generated by Django 5.2.5 on 2025-09-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_tasacomision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(choices=[('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Medio de Acreditación')),
                ('titular_cuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del titular')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de cuenta')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta o IBAN')),
                ('proveedor_billetera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor de billetera')),
                ('billetera_email_telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email o teléfono asociado')),
                ('billetera_titular', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del titular billetera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'ordering': ['id'],
            },
        ),
    ]
