# Generated by Django 5.2.5 on 2025-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioacreditacion',
            name='monto',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
    ]
