# Generated by Django 5.2.5 on 2025-08-22 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('MIN', 'Minorista'), ('CORP', 'Corporativo'), ('VIP', 'VIP')], default='MIN', max_length=10)),
                ('usuario', models.ManyToManyField(related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
