# Generated by Django 5.2.5 on 2025-09-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_usuario_cliente_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el cliente está eliminado lógicamente.'),
        ),
    ]
