# Generated by Django 5.2.5 on 2025-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_is_deleted_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado del registro (activo, eliminado, etc.)', max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('MIN', 'Minorista'), ('CORP', 'Corporativo'), ('VIP', 'VIP')], help_text='Segmento al que aplica la comisión (MIN, CORP, VIP).', max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=3, help_text='Porcentaje de comisión. Ej: 2.5 = 2,5 %.', max_digits=6)),
                ('vigente_desde', models.DateField(help_text='Inclusive')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Inclusive. Vacío = indefinido', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de comisión',
                'verbose_name_plural': 'Tasas de comisión',
                'ordering': ['tipo_cliente', '-vigente_desde', '-id'],
                'indexes': [models.Index(fields=['tipo_cliente', 'vigente_desde'], name='clientes_ta_tipo_cl_be264d_idx'), models.Index(fields=['estado'], name='clientes_ta_estado_091675_idx')],
            },
        ),
    ]
