# Generated by Django 5.2.5 on 2025-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_tasacomision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacomision',
            options={'ordering': ['tipo_cliente', '-vigente_desde', '-id'], 'verbose_name': 'Tasa de descuento', 'verbose_name_plural': 'Tasas de descuento'},
        ),
        migrations.AlterField(
            model_name='tasacomision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, help_text='Porcentaje de descuento. Ej: 2.5 = 2,5 %.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tasacomision',
            name='tipo_cliente',
            field=models.CharField(choices=[('MIN', 'Minorista'), ('CORP', 'Corporativo'), ('VIP', 'VIP')], help_text='Segmento al que aplica el descuento (MIN, CORP, VIP).', max_length=10),
        ),
    ]
