# Generated by Django 5.2.5 on 2025-09-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_tasacomision_options_and_more'),
        ('monedas', '0003_alter_tasacambio_options_tasacambio_es_automatica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitePYG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_por_operacion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LimiteMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_por_operacion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda')),
            ],
            options={
                'unique_together': {('cliente', 'moneda')},
            },
        ),
    ]
