# Generated by Django 5.2.5 on 2025-08-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Rol de Usuario', 'verbose_name_plural': 'Roles de Usuario'},
        ),
    ]
