# Generated by Django 5.2.5 on 2025-09-15 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej.: PYG, USD, BRL', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Usá un código ISO 4217 de 3 letras mayúsculas (ej.: PYG, USD, BRL).', regex='^[A-Z]{3}$')], verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('simbolo', models.CharField(default='₲', max_length=5, verbose_name='Símbolo')),
                ('decimales', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Decimales')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('es_base', models.BooleanField(default=False, verbose_name='¿Es moneda base?')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['-es_base', 'codigo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_base', True)), fields=('es_base',), name='uniq_moneda_base_global')],
            },
        ),
    ]
