# Generated by Django 5.2.5 on 2025-09-15 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Compra')),
                ('venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Venta')),
                ('variacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Variación %')),
                ('base_codigo', models.CharField(default='PYG', max_length=3, validators=[django.core.validators.RegexValidator(message='Usá un código ISO 4217 de 3 letras mayúsculas (ej.: PYG, USD, BRL).', regex='^[A-Z]{3}$')], verbose_name='Base de cotización')),
                ('fuente', models.CharField(blank=True, max_length=120, verbose_name='Fuente')),
                ('ts_fuente', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp (fuente)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_actualizacion'],
                'constraints': [models.UniqueConstraint(fields=('moneda', 'ts_fuente', 'fuente'), name='uniq_tasa_moneda_ts_fuente')],
            },
        ),
    ]
