# Generated by Django 5.2.5 on 2025-09-24 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_tasacambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='es_automatica',
            field=models.BooleanField(default=False, verbose_name='¿Cargada automáticamente?'),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Cotización activa?'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='fuente',
            field=models.CharField(blank=True, help_text='Ej: Banco Central, API Externa, Manual', max_length=120, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='variacion',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Variación %'),
        ),
        migrations.AddIndex(
            model_name='tasacambio',
            index=models.Index(fields=['moneda', 'activa', '-fecha_creacion'], name='monedas_tas_moneda__700279_idx'),
        ),
        migrations.AddIndex(
            model_name='tasacambio',
            index=models.Index(fields=['moneda', 'ts_fuente'], name='monedas_tas_moneda__ccd843_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasacambio',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('moneda',), name='uniq_tasa_activa_por_moneda'),
        ),
    ]
