# Generated by Django 5.2.5 on 2025-09-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_active',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado'),
        ),
    ]
