# Generated by Django 5.2.5 on 2025-09-14 03:30

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymentmethod_is_active_paymentmethod_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='estado',
        ),
    ]
