# Generated by Django 5.2.5 on 2025-09-14 03:40

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_is_deleted_cliente_estado'),
        ('payments', '0003_remove_paymentmethod_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='clientes.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
