# Generated by Django 5.2.5 on 2025-09-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billetera_email_telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email o teléfono asociado'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billetera_titular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del titular billetera'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta o IBAN'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera Digital')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Método de Pago'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='proveedor_billetera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor de billetera'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV/CVC'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_marca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca de tarjeta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre en tarjeta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de tarjeta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_vencimiento',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del titular'),
        ),
    ]
