# Generated by Django 5.2.5 on 2025-09-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentmethod_banco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['id'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
    ]
