# Generated by Django 5.2.5 on 2025-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_beneficiario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_moneda',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de cheque'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cheque_orden',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Orden (Casa Matriz, dirección incluida)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera'), ('cheque', 'Cheque')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Método de Pago'),
        ),
    ]
