# Generated by Django 5.2.5 on 2025-09-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentmethod_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='monto',
        ),
    ]
