# Generated by Django 5.2.5 on 2025-09-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_role_options_alter_userrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el usuario está eliminado lógicamente.'),
        ),
    ]
