# Generated by Django 5.2.5 on 2025-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el rol está eliminado lógicamente.'),
        ),
    ]
