# Generated by Django 5.2.5 on 2025-09-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_role_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='role',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado del rol (activo, eliminado, suspendido, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado del usuario (activo, eliminado, suspendido, etc.)', max_length=20),
        ),
    ]
