# Generated by Django 5.2.5 on 2025-08-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
