# Generated by Django 5.2.5 on 2025-09-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_limitepyg_limitemoneda'),
        ('medios_acreditacion', '0003_remove_medioacreditacion_monto'),
        ('monedas', '0003_alter_tasacambio_options_tasacambio_es_automatica_and_more'),
        ('payments', '0009_remove_paymentmethod_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('monto_operado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_pyg', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='clientes.cliente', verbose_name='Cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='payments.paymentmethod', verbose_name='Medio de Pago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='monedas.moneda', verbose_name='Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='clientes.cliente', verbose_name='Cliente')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='medios_acreditacion.medioacreditacion', verbose_name='Medio de Acreditación')),
                ('transaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='transaccion.transaccion', verbose_name='Transacción')),
            ],
        ),
    ]
