# Generated by Django 5.2.5 on 2025-09-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_paymentmethod_monto'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='payments.paymentmethod', verbose_name='Medio de Pago'),
        ),
    ]
