# Generated by Django 5.2.5 on 2025-09-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0003_remove_medioacreditacion_monto'),
        ('transaccion', '0002_alter_transaccion_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='medios_acreditacion.medioacreditacion', verbose_name='Medio de Acreditación'),
        ),
    ]
