# Generated by Django 5.2.5 on 2025-10-17 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_alter_movimiento_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
